spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

  sql:
    init:
      mode: always

  paypal:
    mode: ${PROD_PAYPAL_MODE}
    client:
      id: ${PROD_PAYPAL_CLIENT_ID}
      secret: ${PROD_PAYPAL_CLIENT_SECRET}

  mail:
    host: ${PROD_MAIL_HOST}
    port: ${PROD_MAIL_PORT}
    username: ${PROD_MAIL_USERNAME}
    password: ${PROD_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true